= Цепочек не найдется?
:hp-alt-title: Could you find some chains

Еще в 2009 году Стефан Эссер предложил новую технику для эксплуатации уязвимостей типа PHP Object Injection (POI). Техника заключалась в повторном использовании кода уязвимого приложения по аналогии с техникой ROP при эксплуатации ошибок работы с памятью при наличии ASLR. Суть техники заключается в построении последовательности вложенных объектов из множества определенных в уязвимом приложении, в каждом из которых атакующим контролируются все поля, что в итоге позволяет вызывать методы вложенных классов, которые изначально не предполагались разработчиком к вызову в таком контексте. 
С тех пор поиск подобных цепочек для эксплуатации уязвимостей класса POI в больших приложениях по-прежнему остается сложной задачей и решается вручную.

Попытки автоматизировать поиск цепочек уже предпринимались: среди наиболее значимых можно отметить статический анализатор от команды https://www.ripstech.com[RIPs Technologies]. В статье от команды RIPS Technologies подробно описан метод поиска цепочек. К сожалению, для сообщества реализация метода недоступна, так как основывается на результатах работы их проприетарного коммерческого статического анализатора.

Так же сообщество поддерживает библиотеку известных цепочек https://github.com/ambionics/phpggc[PHPGGC], в которую любой желающий может сделать Pull-request с найденной им цепочкой. Последнее время в проекте появляется много новых цепочек, что подтверждает актуальность задачи их поиска.

В рамках https://github.com/dsp25no/blog.dsp25no.ru/raw/gh-pages/data/Master_thesis.pdf[магистерской диссертации] был разработан метод и реализован https://github.com/dsp25no/php-chain[инструмент] для поиска цепочек.